config/routes.rb
Rails.application.routes.draw do
  get 'flats', to: 'flats#index', as: :flats
  get 'flats/:id', to: 'flats#show', as: :flat

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
require 'open-uri'

class FlatsController < ApplicationController
  def index
    @flats = parse_flats
  end

  def show
    @flat = parse_flats.find do |flat|
      flat['id'].to_i == params[:id].to_i
    end
  end

  private

  def parse_flats
    JSON.parse(open('https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json').read)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h1 class="text-center">Feel at home, anywhere</h1>


<div class="flats">
  <div class="row">
    <% @flats.each do |flat| %>
      <div class="col-xs-12 col-sm-4">
        <div class="flat card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= flat['imageUrl'] %>');">
          <div class="card-description">
            <h2><%= flat['name'] %></h2>
            <p><%= flat['price'] %> €</p>
          </div>
          <%= link_to '', flat_path(flat['id']), class: 'card-link' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/show.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= @flat['imageUrl'] %>');">
  <div class="banner-content">
    <h1><%= @flat['name'] %></h1>
    <p><%= @flat['price'] %> € per night</p>
    <%= link_to 'Back to list', flats_path, class: 'btn btn-primary btn-lg' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAirbnbClone</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>